### ISSUE TITLE
Not working at all ! why？

### ISSUE THREAD

**Issue by lixueqin-4119** [rupa/z#313]
**reappears**
```js
Step 1.git clone https://github.com/rupa/z.git
Step 2.pwd  // /Users/mac/z/z.sh
Step 3.open ~/.bashrc 
add:
. /Users/mac/z/z.sh
alias j='z'
```
<img width="280" alt="屏幕快照 2022-04-29 上午4 10 00" src="https://user-images.githubusercontent.com/54841759/165837266-f4c8da9d-c4d8-45b2-92c9-536e42ce75ad.png">

<img width="280" alt="屏幕快照 2022-04-29 上午4 07 45" src="https://user-images.githubusercontent.com/54841759/165836918-cea0d316-68b7-418f-8839-3fc32e99e35c.png">

**Comment by tanducmai** [comment]
You can try removing the last line, it works on my machine without alias.

**Comment by abetusk** [comment]
Is this resolved?

There are three things to try.

First, in an interactive shell, try to load `z.sh`, alias and then try. So see if the following works:

```bash
$ . /Users/mac/z/z.sh
$ alias j='z'
$ j
```

Second, try reloading the `.bashrc` file or try opening a new terminal to see if it works:

```bash
$ . .bashrc
$ j
```

Third, confirm you are actually using `bash` instead of some other shell (like `zsh`).

```bash
$ echo $SHELL
$ ps -p $$
```

If this is not `bash` then presumably the `.bashrc` isn't being read and you should alter the appropriate shell rc file that is executed on shell load.

I'm not that familiar with Mac but from what I gather `zsh` might be another commonly used shell.
